<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestSuit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f4447e6c-83b6-4b07-93fa-7cfda68a387d</testSuiteGuid>
   <testCaseLink>
      <guid>b1d2d656-3559-478b-8f00-3720ce52422b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e9707b47-3457-4708-8764-ef70a862faf3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e9707b47-3457-4708-8764-ef70a862faf3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>47eae9ef-cb41-46c5-b529-84be5d484f17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e9707b47-3457-4708-8764-ef70a862faf3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8aaeb231-793a-497c-aa9f-a79ceb6ebd3d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
