<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AcceptedW3CCapabilityKeys</name>
   <tag></tag>
   <elementGuidId>6c1b0a02-c695-4c8b-a2ac-eae13864f2c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;class in org.openqa.selenium&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='class-summary.tabpanel']/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;AcceptedW3CCapabilityKeys&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94b05e87-0ccc-4d4e-9ecb-0c911834ac97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>AcceptedW3CCapabilityKeys.html</value>
      <webElementGuid>7f832c21-3688-4e67-8d58-c7203a11878f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium</value>
      <webElementGuid>34e4d424-a89f-496a-848b-d8b60adbdac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AcceptedW3CCapabilityKeys</value>
      <webElementGuid>a37fffb4-9893-4851-a703-690f5d286820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary.tabpanel&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first even-row-color class-summary class-summary-tab2&quot;]/a[1]</value>
      <webElementGuid>42b7c24c-9fc3-4389-8155-576935f83e12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary.tabpanel']/div/div[3]/a</value>
      <webElementGuid>923d2301-a3cc-40b5-8e1a-cf91bc09787b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AcceptedW3CCapabilityKeys')]</value>
      <webElementGuid>149e5e87-69bf-4f4d-8819-89b417151ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::a[1]</value>
      <webElementGuid>8a1de91d-5da8-49c9-ab6e-dea52f1b6700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class'])[2]/following::a[1]</value>
      <webElementGuid>6274c720-6824-46cf-bb7c-4f90b7d4a12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert'])[1]/preceding::a[1]</value>
      <webElementGuid>7fc84691-4c75-43a3-bbfb-ff9e1b44bb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Architecture'])[1]/preceding::a[2]</value>
      <webElementGuid>9e2ad94b-4282-40d9-8c3f-45ff473eccde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AcceptedW3CCapabilityKeys']/parent::*</value>
      <webElementGuid>dc48a214-34f4-4b12-b7f7-f063d3c07b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'AcceptedW3CCapabilityKeys.html')]</value>
      <webElementGuid>0f561747-5e0b-4feb-ba6e-a75be6de4cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>1583ecdb-3aa6-46ae-ad9b-c2a607f15108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'AcceptedW3CCapabilityKeys.html' and @title = 'class in org.openqa.selenium' and (text() = 'AcceptedW3CCapabilityKeys' or . = 'AcceptedW3CCapabilityKeys')]</value>
      <webElementGuid>1a7c5cd3-e714-4a48-8101-a698937951b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
