<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Instance Methods</name>
   <tag></tag>
   <elementGuidId>7edf24e7-faf2-4665-abe5-b8f9cfe9f4b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#method-summary-table-tab2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='method-summary-table-tab2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Instance Methods&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba52454c-07c0-47a8-ad8f-b14333a37a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>method-summary-table-tab2</value>
      <webElementGuid>9d6218cb-7dec-462c-8267-0bc714416a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3653f5dc-fd94-490a-b431-707abe89beb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a745e69d-4e04-4834-8833-998f293470cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>method-summary-table.tabpanel</value>
      <webElementGuid>7a68d1cc-fdf4-4d6d-ab27-9df8ceeebb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>55c0aa0a-b5df-49bb-b7f3-655583892018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>switchTab(event)</value>
      <webElementGuid>dd8813b2-c5fa-4ed8-90b8-4274823ba8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show('method-summary-table', 'method-summary-table-tab2', 3)</value>
      <webElementGuid>dec86eb8-30f2-4c88-a5e0-4b9e5396a8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-tab</value>
      <webElementGuid>13d2707a-de17-4e34-8c2f-1962f9d15fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instance Methods</value>
      <webElementGuid>b68beb25-f213-4e93-8a4e-372404f82445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;method-summary-table-tab2&quot;)</value>
      <webElementGuid>67e8914a-8f64-4c5a-8077-1bde23bd1f68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='method-summary-table-tab2']</value>
      <webElementGuid>33a11f59-5c85-4acb-a917-4718f061eaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='method-summary-table']/div/button[2]</value>
      <webElementGuid>ad5456d2-6baf-493c-8fbe-1c9cc0afbd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Methods'])[1]/following::button[1]</value>
      <webElementGuid>2a08b13b-d507-4b1b-a260-65db5b084126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method Summary'])[1]/following::button[2]</value>
      <webElementGuid>d48f4084-f2d0-4e4e-b718-3d2d220f18ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concrete Methods'])[1]/preceding::button[1]</value>
      <webElementGuid>a8024e0d-fc2b-4ce9-baab-fa9787e70a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modifier and Type'])[1]/preceding::button[2]</value>
      <webElementGuid>f99cf0a6-dfa1-4c62-a0d8-c7fc2f8f2ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Instance Methods']/parent::*</value>
      <webElementGuid>52f6a012-3354-4b0f-930d-d283d8437815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>dd0d7d12-7f02-4f6d-b976-c972c236bdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'method-summary-table-tab2' and (text() = 'Instance Methods' or . = 'Instance Methods')]</value>
      <webElementGuid>89810f05-21f5-4cbb-a531-c6613620f958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
