<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Next</name>
   <tag></tag>
   <elementGuidId>1c0805e3-0c33-41bf-ad27-721baf686e92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.w3-right.w3-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Next ❯&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f44f3ca-653f-4d94-adec-9c4be6e58526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-right w3-btn</value>
      <webElementGuid>e29d9fb8-ba2f-467c-b6b6-e8a95b6257bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>sql_count.asp</value>
      <webElementGuid>b4d0ded1-f16d-4ee0-991e-980f1293685d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next ❯</value>
      <webElementGuid>5bfd1f43-3c0c-4b56-9bb6-a2a5943ce388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;w3-clear nextprev&quot;]/a[@class=&quot;w3-right w3-btn&quot;]</value>
      <webElementGuid>08c56aa0-c31f-41ad-b156-dfe362c8fcc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/a[2]</value>
      <webElementGuid>a1597a7d-7ccc-4475-b536-f135d444265b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Next ❯')]</value>
      <webElementGuid>86213cb8-0033-4b2c-813d-bdcccd643a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='❮ Previous'])[1]/following::a[1]</value>
      <webElementGuid>a405ad65-91e0-4274-b0d9-67c825eedbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MIN() and MAX()'])[1]/following::a[2]</value>
      <webElementGuid>8250662f-03bc-4dd6-a9d3-e1d1799f2f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The SQL MIN() and MAX() Functions'])[1]/preceding::a[1]</value>
      <webElementGuid>f330df77-06c3-495d-bdb3-8d9cb866691f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MIN()'])[1]/preceding::a[1]</value>
      <webElementGuid>3dc8a1b1-3aa1-461e-b2e5-b9b483378d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next ❯']/parent::*</value>
      <webElementGuid>e2e11d50-c000-4bb4-9729-c4c19f029ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'sql_count.asp')])[3]</value>
      <webElementGuid>b09ef689-879f-4e90-bf80-507e279e5d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a[2]</value>
      <webElementGuid>7aba2d18-b55f-4eea-bc8a-6c9d67757a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'sql_count.asp' and (text() = 'Next ❯' or . = 'Next ❯')]</value>
      <webElementGuid>b7a52729-f336-4d96-bee3-2c461fc6e641</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
