<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SQL Select Top</name>
   <tag></tag>
   <elementGuidId>87993e74-6d03-4c8e-ae6e-c9ac2ce5c552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftmenuinnerinner']/a[15]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leftmenuinnerinner > a:nth-of-type(15)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; SQL Select Top&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c337db7d-0766-4f96-93ed-10b22277c7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>7fe0478c-d64b-4ce2-ba69-2176fe9233e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>sql_top.asp</value>
      <webElementGuid>06761b10-cdb9-417c-9f4d-5e816569ab0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SQL Select Top</value>
      <webElementGuid>7696370a-d17a-4881-9c66-70d5dfb3dd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftmenuinnerinner&quot;)/a[15]</value>
      <webElementGuid>73c2b570-af17-4ed5-ae6d-006a518ea32d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftmenuinnerinner']/a[15]</value>
      <webElementGuid>96bb238c-dfc8-47a2-bcc4-e85248a7348d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SQL Select Top')]</value>
      <webElementGuid>30d2f152-d8f6-45e0-b638-926501246df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL Delete'])[1]/following::a[1]</value>
      <webElementGuid>1bad266b-c707-450a-b2d0-9e9bf18a4d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL Update'])[1]/following::a[2]</value>
      <webElementGuid>508bb930-05a8-4553-8ec7-bfc9233763f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL Aggregate Functions'])[1]/preceding::a[1]</value>
      <webElementGuid>7732fbef-b3b5-4073-8867-3849cb49c1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQL Min and Max'])[1]/preceding::a[2]</value>
      <webElementGuid>0bd44d7b-029c-4f0e-ac58-cbdfc84e7007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SQL Select Top']/parent::*</value>
      <webElementGuid>abeeb5ba-e7d1-4275-a960-4f84112a4782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'sql_top.asp')]</value>
      <webElementGuid>0ec86bfd-3827-46c6-9d96-f9c10a31d67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a[15]</value>
      <webElementGuid>8cba7525-e0be-4213-9c84-7657e386c531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'sql_top.asp' and (text() = 'SQL Select Top' or . = 'SQL Select Top')]</value>
      <webElementGuid>f01a5991-3080-4a86-a7b6-1017fe6a03ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
